/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-container": "#bc4800",
        "outline-variant": "#c3c6d7",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-surface": "#191b23",
        "primary": "#004ac6",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "surface": "#faf8ff",
        "surface-dim": "#d9d9e5",
        "tertiary": "#943700",
        "on-surface-variant": "#434655",
        "secondary-container": "#645efb",
        "background": "#faf8ff",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#3323cc",
        "on-background": "#191b23",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3039",
        "on-tertiary-container": "#ffede6",
        "on-secondary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "surface-container-high": "#e7e7f3",
        "surface-container": "#ededf9",
        "error": "#ba1a1a",
        "secondary": "#4b41e1",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#0f0069",
        "primary-container": "#2563eb",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed": "#360f00",
        "surface-variant": "#e1e2ed",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b4c5ff",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#e2dfff",
        "surface-tint": "#0053db",
        "outline": "#737686",
        "surface-container-highest": "#e1e2ed",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#ffdbcd"
      },
      spacing: {
        "md": "1rem",
        "sm": "0.5rem",
        "gutter": "1rem",
        "lg": "1.5rem",
        "xl": "2.5rem",
        "base": "4px",
        "xs": "0.25rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        "body-base": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
